name = "consumePack"
author = "consume"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebd6ef0b057074767f6e232f2662e2651cb4c17ea33c3a43c622da4a63e39dfd"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.3.0"
