name = "consumePack"
author = "consume"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddbaeeab0c4e6e274db0e79ae19c0be1078f1026298187ac4fcce757672a85e7"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "0.3.0"
