name = "consumePack"
author = "consume"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f1d99f71bfe0ee3ad863c04ca53c6c43e32c9ce0c9e1b430b330483f6878eff"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.3.0"
