name = "consumePack"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc75efb08c494c3039702038f532f9db770dfcf4edbaaa724a876cac3ad94d85"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.3.0"
