name = "consumePack"
author = "consume"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b7a26778a7d9e536c59ce4714962e79fce80defc83141691faa1fb03ebbd02d"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
unsup = "0.3.0"
