name = "consumePack"
author = "consume"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc7c0a750b62f0a79bfaa94257ca29ee1362e320bad8e7e172c37435fb2dc8a7"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.3.0"
