name = "consumePack"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8867a6e0a47954af9e6e0b4131e6408d0a6244836554d378660170b645a984ac"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.3.0"
